from django.urls import path
from .views import payment_view, take_exam, exam_results, exam_questions, exam_list, exam_detail, student_dashboard,  view_results, student_analytics, subscription_plans, initialize_payment, verify_payment, payment_success, subscription_status, recent_exams, exam_result
from .views import performance_view
from .views  import subscription_management, save_subscription, cancel_subscription
from .views import student_management, add_student, student_details, block_student, unblock_student
# from .views import transaction_history, transaction_details, export_transactions, generate_report
from .views import exam_management, save_exam, delete_exam, add_question, get_questions, delete_question
from .views import support_management, create_ticket, view_ticket, respond_ticket, resolve_ticket
from .views import student_support
from . import views

urlpatterns = [
    path('student/', student_dashboard, name='student_dashboard'),
    # path('create-question/', create_question, name='create_question'),
    path('view-results/<int:exam_id>/', view_results, name='view_results'),
    path('analytics/', student_analytics, name='student_analytics'),
    # path('create_exam/', create_exam, name='create_exam'),
    # path('create_question/', create_question, name='create_question'),
    path('exam/<int:exam_id>/', exam_detail, name='exam_detail'),
    path('take_exam/<int:exam_id>/', take_exam, name='take_exam'),
    path('exam_list/', exam_list, name='exam_list'),
    path('exam/<int:exam_id>/questions/', exam_questions, name='exam_questions'),
    # path('exam/<int:exam_id>/take/<int:question_index>/', take_exam, name='take_exam'),
    # path('exam/<int:exam_id>/results/', exam_results, name='exam_results'),
    path('payment/<int:exam_id>/', payment_view, name='pay_exam'),
    # path('subscription/plans/', views.subscription_plans_view, name='subscription_plans'),
    path('payment/initialize/', views.initialize_payment, name='initialize_payment'),
    path('payment/verify/<str:tx_ref>/', views.verify_payment, name='verify_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/failed/', views.payment_failed, name='payment_failed'),
    path('subscription/status/', subscription_status, name='subscription_status'),
    path('recent-exams/', recent_exams, name='recent_exams'),
    path('exam/<int:exam_id>/result/', exam_result, name='exam_result'),
    path('performance/', performance_view, name='performance'),
    path('subscriptions/', subscription_management, name='subscription_management'),
    path('subscriptions/save/', save_subscription, name='save_subscription'),
    path('subscriptions/cancel/', cancel_subscription, name='cancel_subscription'),
    path('students/', student_management, name='student_management'),
    path('students/add/', add_student, name='add_student'),
    path('students/details/', student_details, name='student_details'),
    path('students/block/', block_student, name='block_student'),
    path('students/unblock/', unblock_student, name='unblock_student'),
    # path('transactions/', transaction_history, name='transaction_history'),
    # path('transactions/details/', transaction_details, name='transaction_details'),
    # path('transactions/export/', export_transactions, name='export_transactions'),
    # path('transactions/report/', generate_report, name='generate_report'),

    path('main-admin/exams/', views.exam_management, name='exam_management'),
    path('main-admin/exams/<int:exam_id>/', views.get_exam, name='get_exam'),
    path('main-admin/exams/save/', views.save_exam, name='save_exam'),
    path('main-admin/exams/delete/', views.delete_exam, name='delete_exam'),
    path('main-admin/exams/questions/add/', views.add_question, name='add_question'),
    path('main-admin/exams/questions/list/', views.get_questions, name='get_questions'),
    path('main-admin/exams/questions/delete/', views.delete_question, name='delete_question'),
    path('support/', support_management, name='support_management'),
    path('support/ticket/create/', create_ticket, name='create_ticket'),
    path('support/ticket/<int:ticket_id>/', view_ticket, name='view_ticket'),
    path('support/ticket/respond/', respond_ticket, name='respond_ticket'),
    path('support/ticket/resolve/', resolve_ticket, name='resolve_ticket'),
    path('student/support/', views.student_support, name='student_support'),
    path('student/support/ticket/<int:ticket_id>/', views.student_view_ticket, name='student_view_ticket'),
    path('student/support/create/', views.create_ticket, name='create_ticket'),
    path('staff/support/', views.admin_support, name='admin_support'),
    path('staff/support/ticket/<int:ticket_id>/', views.admin_view_ticket, name='admin_view_ticket'),
    path('support/respond/', views.respond_ticket, name='respond_ticket'),
    path('support/resolve/', views.resolve_ticket, name='resolve_ticket'),
    path('support/cancel/', views.cancel_ticket, name='cancel_ticket'),
    path('main-admin/users/', views.student_management, name='admin_student_management'),
    path('main-admin/users/<int:user_id>/', views.get_user_details, name='get_user_details'),
    path('main-admin/users/toggle-status/', views.toggle_user_status, name='toggle_user_status'),
    path('main-admin/users/delete/', views.delete_user, name='delete_user'),
    path('main-admin/teachers/', views.teacher_management, name='teacher_management'),
    path('main-admin/teachers/<int:teacher_id>/', views.get_teacher_details, name='get_teacher_details'),
    path('main-admin/teachers/add/', views.add_teacher, name='add_teacher'),
    path('main-admin/teachers/toggle-status/', views.toggle_teacher_status, name='toggle_teacher_status'),
    path('main-admin/teachers/delete/', views.delete_teacher, name='delete_teacher'),
    path('main-admin/subscriptions/', views.subscription_management, name='subscription_management'),
    path('main-admin/subscriptions/<int:subscription_id>/', views.get_subscription, name='get_subscription'),
    path('main-admin/subscriptions/save/', views.save_subscription, name='save_subscription'),
    path('main-admin/subscriptions/toggle-renew/', views.toggle_subscription_renew, name='toggle_subscription_renew'),
    path('main-admin/subscriptions/cancel/', views.cancel_subscription, name='cancel_subscription'),
    # path('main-admin/transactions/', views.transaction_history, name='transaction_history'),
    # path('main-admin/transactions/details/', views.transaction_details, name='transaction_details'),
    # path('main-admin/transactions/export/', views.export_transactions, name='export_transactions'),
    # path('main-admin/transactions/report/', views.generate_report, name='generate_report'),
    # path('main-admin/transactions/refund/', views.initiate_refund, name='initiate_refund'),
    path('main-admin/subscription-plans/', views.manage_subscription_plans, name='manage_subscription_plans'),
    path('api/subscription-plan/<int:plan_id>/', views.subscription_plan_detail, name='subscription_plan_detail'),
    # path('payment/complete/<str:tx_ref>/', views.payment_complete, name='payment_complete'),
    # path('payment/webhook/', views.payment_webhook, name='payment_webhook'),
    path('subscription/plans/', subscription_plans, name='subscription_plans'),
    path('student/support/', views.student_support, name='student_support'),
    path('student/support/ticket/<int:ticket_id>/', views.student_view_ticket, name='student_view_ticket'),
    path('student/support/create/', views.create_ticket, name='create_ticket'),
    path('transaction-history/', views.transaction_history, name='transaction_history'),
]   
